package ProjetoSI

import ProjetoSI.*;
import robocode.*;
import robocode.ScannedRobotEvent;

// Consultar ações na lista de ações
query "consulta_acoes"
	acao: AcaoTeam()
end

declare Vitima
   nome: String
   x: double
   y: double
   distancia: double
end

rule "Mais de uma ação ao mesmo tempo --> Escolhe a de maior prioridades"
	when
		$acao1: AcaoTeam($tipo: tipo, $prioridade1: prioridade)
		$acao2: AcaoTeam(tipo==$tipo, $prioridade2: prioridade)
		eval ($prioridade1 > $prioridade2)
	then
		retract($acao2);     // Elimina la acao menos prioritaria 
		System.out.println("Depurar Acoes");
end

rule "Messagem Recebida"
	when
		$status: EstadoRobot()
		$messageEvent: MessageEvent()
	then
		double angulo = Util.recuperarCoordenada($status, $messageEvent);
		System.out.println("Droid Mensagem Recebida = "+angulo);
		insert(new AcaoTeam(AcaoTeam.GIRAR_CANHAO_DIR, angulo, 5));
		insert (new AcaoTeam(AcaoTeam.DISPARAR, Math.min(Rules.MAX_BULLET_POWER, 0.10*$status.getEnergy()), 5));
		System.out.println("> Disparar...");
end

/*
rule "Bateu em outro robo --> Retrocede 200 pixels"
	when
		HitRobotEvent($nome: name, $anguloRelativo: bearing)
	then
		insert(new AcaoTeam(AcaoTeam.GIRAR_TANQUE_DIR, (- $anguloRelativo), 6));
		insert(new AcaoTeam(AcaoTeam.RETROCEDER, 200, 5));
		System.out.println("Choque Com outro Robo");
end

rule "Bateu no muro --> Retrocede 200 pixels"
	when
		HitWallEvent($anguloRelativo: bearing)
	then
		insert(new AcaoTeam(AcaoTeam.GIRAR_TANQUE_DIR, (- $anguloRelativo), 6));
		insert(new AcaoTeam(AcaoTeam.AVANCAR, 200, 5));
		System.out.println("Choque Com Muro");
end

rule "Parado --> Movimento Aleatório"
	when
		EstadoRobot( distanceRemaining == 0 )
		$batalha: EstadoBatalha()
		not (exists(HitRobotEvent()))
		not (exists(HitWallEvent()))
	then
		insert(new AcaoTeam(AcaoTeam.GIRAR_TANQUE_DIR, (360*Math.random() - 180), 2));
		insert(new AcaoTeam(AcaoTeam.GIRAR_CANHAO_DIR, (360*Math.random() - 180), 2));
		double avance = Math.min($batalha.getLarguraCampo(), $batalha.getAlturaCampo())*Math.random();
		insert(new AcaoTeam(AcaoTeam.AVANCAR, avance, 2));
		System.out.println("Movimento Aleatorio");
end
*/